version: '3'
services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crmvue-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: crmproj
      DB_USERNAME: root
      DB_PASSWORD: Indonesia2024*

  # Vue Frontend (Production)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: crmvue-frontend
    ports:
      - "8081:8080"
    depends_on:
      - backend

  # Vue Frontend (Development)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: crmvue-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: crmvue-mysql
    environment:
      MYSQL_DATABASE: crmproj
      MYSQL_ROOT_PASSWORD: Indonesia2024*
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pIndonesia2024*"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 